package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/weeb-vip/news-ingest/graph/generated"
	"github.com/weeb-vip/news-ingest/graph/model"
)

// FindAnimeByID is the resolver for the findAnimeByID field.
func (r *entityResolver) FindAnimeByID(ctx context.Context, id string) (*model.Anime, error) {
	// The router resolves Anime elsewhere (anime-api owns it) and calls here only to attach
	// news. So this returns the reference itself — no lookup — and Anime.news does the work.
	// Querying an anime table we do not own would reintroduce exactly the coupling this
	// service was split out to remove.
	return &model.Anime{ID: id}, nil
}

// FindAnimeNewsByID is the resolver for the findAnimeNewsByID field.
func (r *entityResolver) FindAnimeNewsByID(ctx context.Context, id string) (*model.AnimeNews, error) {
	row, err := r.Store.NewsByID(ctx, id)
	if err != nil {
		return nil, err
	}
	if row == nil {
		return nil, nil // a dangling reference is not an error; the field resolves to null
	}
	return toGraph(*row), nil
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
