package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/weeb-vip/news-ingest/graph/generated"
	"github.com/weeb-vip/news-ingest/graph/model"
	"github.com/weeb-vip/news-ingest/internal/store"
)

// News is the resolver for the news field.
func (r *animeResolver) News(ctx context.Context, obj *model.Anime) ([]*model.AnimeNews, error) {
	rows, err := r.Store.NewsForAnime(ctx, obj.ID)
	if err != nil {
		return nil, err
	}
	return toGraphAll(rows), nil
}

// LatestNews is the resolver for the latestNews field.
func (r *queryResolver) LatestNews(ctx context.Context, limit *int, offset *int, category *string, language *string) (*model.NewsFeed, error) {
	rows, total, err := r.Store.LatestNews(ctx, deref(limit, 20), deref(offset, 0),
		store.NewsFilter{Category: category, Language: language})
	if err != nil {
		return nil, err
	}
	return &model.NewsFeed{Items: toGraphAll(rows), Total: int(total)}, nil
}

// Anime returns generated.AnimeResolver implementation.
func (r *Resolver) Anime() generated.AnimeResolver { return &animeResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type (
	animeResolver struct{ *Resolver }
	queryResolver struct{ *Resolver }
)

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func deref(v *int, fallback int) int {
	if v == nil {
		return fallback
	}
	return *v
}
*/
