// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Anime struct {
	ID string `json:"id"`
	// AI-researched news for this anime
	News []*AnimeNews `json:"news,omitempty"`
}

func (Anime) IsEntity() {}

// One AI-researched news item about an anime.
type AnimeNews struct {
	ID            string  `json:"id"`
	AnimeID       string  `json:"animeId"`
	Title         string  `json:"title"`
	Summary       *string `json:"summary,omitempty"`
	Category      string  `json:"category"`
	SourceURL     *string `json:"sourceUrl,omitempty"`
	SourceName    *string `json:"sourceName,omitempty"`
	PublishedDate *string `json:"publishedDate,omitempty"`
	EpisodeNumber *int    `json:"episodeNumber,omitempty"`
	MalID         *int    `json:"malId,omitempty"`
	// ISO 639-1 code of the source article. The summary is always English.
	Language *string `json:"language,omitempty"`
	// Media the article points at — a PV, the official site, an announcement post.
	References []*NewsReference `json:"references,omitempty"`
}

func (AnimeNews) IsEntity() {}

// A page of the site-wide feed.
type NewsFeed struct {
	Items []*AnimeNews `json:"items"`
	// Total matching the filters, for pagination. Not the number returned.
	Total int `json:"total"`
}

type NewsReference struct {
	// Coarse bucket derived from the link's host: video, post or site.
	Kind  string `json:"kind"`
	Title string `json:"title"`
	URL   string `json:"url"`
}

type Query struct {
}
